# 作成時の最高値で設定
Metrics/MethodLength:
  Max: 45
  Exclude:
  - 'lib/rbnet/resource/icmp_time_exceeded.rb'

# 作成時の最高値で設定
Metrics/AbcSize:
  Max: 45

# 作成時の最高値で設定
Metrics/ClassLength:
  Max: 304

# 作成時の最高値で設定
Metrics/CyclomaticComplexity:
  Max: 15

# 作成時の最高値で設定
Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true
  Exclude:
  - 'lib/rbnet/resource/icmp_time_exceeded.rb'

# 作成時の最高値で設定
Metrics/PerceivedComplexity:
  Max: 14

# 改行が難しい場合もあるため許容
# 参考 https://github.com/rubocop-hq/rubocop-jp/issues/32
Metrics/LineLength:
  Max: 145

Metrics/BlockLength:
  Max: 30

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# whenのbodyが空なのを許可する
Lint/EmptyWhen:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# operatorの周りを単一スペースではない場合も許可
Layout/SpaceAroundOperators:
  Enabled: false

# 余計なスペースを許可
Layout/ExtraSpacing:
  Enabled: false

# 条件にtrueを使用できるようにする
Lint/LiteralAsCondition:
  Enabled: false

# 無限ループを許可
Style/InfiniteLoop:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/HashSyntax:
  Exclude:
  - "Rakefile"

Style/AccessorGrouping:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/CaseEquality:
  Enabled: false

# グローバル変数の許可
GlobalVars:
  AllowedVariables: [$arp_table]
