
Vagrant.configure('2') do |config|
  config.vm.define :node1 do |node|
    node.vm.box = 'centos/7'
    node.vm.network :private_network, ip: '192.168.10.2', subnet: '24',
      virtualbox__intnet: 'net_a'
    node.vm.network :private_network, ip: '192.168.20.2', subnet: '24',
      virtualbox__intnet: 'net_b'
    node.vm.network :private_network, ip: '192.168.30.2', subnet: '24',
      virtualbox__intnet: 'net_c'
    node.vm.network :private_network, ip: '192.168.40.2', subnet: '24',
      virtualbox__intnet: 'net_d'
    node.vm.synced_folder '/Users/nobo/rbnet', '/vagrant', type:'virtualbox'
    node.vm.provision "shell", path: "setup_rbenv.sh"
  end

  config.vm.define :node2 do |node|
    node.vm.box = 'centos/7'
    node.vm.network :private_network, ip: '192.168.10.3', subnet: '24',
      virtualbox__intnet: 'net_a'
  end

  config.vm.define :node3 do |node|
    node.vm.box = 'centos/7'
    node.vm.network :private_network, ip: '192.168.20.3', subnet: '24',
      virtualbox__intnet: 'net_b'
  end

  config.vm.define :node4 do |node|
    node.vm.box = 'centos/7'
    node.vm.network :private_network, ip: '192.168.30.3', subnet: '24',
      virtualbox__intnet: 'net_c'
    node.vm.network :private_network, ip: '192.168.40.2', subnet: '24',
      virtualbox__intnet: 'net_d'
    node.vm.synced_folder './../', '/vagrant', type:'virtualbox'
    node.vm.provision "shell", path: "setup_rbenv.sh"
  end

  config.vm.define :node5 do |node|
    node.vm.box = 'centos/7'
    node.vm.network :private_network, ip: '192.168.40.3', subnet: '24',
      virtualbox__intnet: 'net_d'
  end
end
