version: '2'
services:
  node1:
    build: ../node1
    volumes:
      - ../../:/rbnet
    tty: true
    privileged: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - net_a
      - net_b
  node2:
    build: ../node2
    volumes:
      - ../../:/rbnet
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - net_a
  node3:
    build: ../node3
    volumes:
      - ../../:/rbnet
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - net_b
networks:
  net_a:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1
  net_b:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
        - subnet: 2001:db8:2::/64
          gateway: 2001:db8:2::1
